version: "3.2"
services:
    betfrcwager:
        container_name: betfrcwager
        image: ppolis22/betfrcwager
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://betfrcwager-postgres:5432/betfrcwager
            BUZZ_APP_ODDS_SERVICE: betfrcodds:8080
        ports:
            - "8081:8081"
        networks:
            - internal
        restart: unless-stopped
    betfrcwager-postgres:
        container_name: betfrcwager-postgres
        image: postgres
        environment:
            POSTGRES_USER: buzz
            POSTGRES_PASSWORD: buzz
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5433:5432"
        networks:
            - internal
        restart: unless-stopped
    betfrcwager-pgadmin:
        container_name: betfrcwager-pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5051:80"
        networks:
            - internal
        restart: unless-stopped

networks:
    internal:
        external: true

volumes:
    postgres:
    pgadmin: